
---

- hosts: localhost
  become: true
  tasks:
  - name: create CA key
    openssl_privatekey:
      path: /etc/ssl/CA_key.pem
    register: ca_key

  - name: create the CA CSR
    openssl_csr:
      path: /etc/ssl/CA.csr
      privatekey_path: "{{ ca_key.filename }}"
      common_name: "my-ca"
    register: ca_csr

  - name: sign the CA CSR
    openssl_certificate:
      path: /etc/ssl/CA.crt
      csr_path: "{{ ca_csr.filename }}"
      privatekey_path: "{{ ca_key.filename }}"
      provider: selfsigned
    register: ca_crt

...





    
